import React from "react";
import { Link } from "react-scroll";

export default function ShopParts() {
  const data = [
    { part: "110 Volt Accessory Power Outlet" },
    { part: "4WD Actuator" },
    { part: "4WD Actuator Valve" },
    { part: "4WD Disconnect" },
    { part: "4WD Hub Locking Solenoid" },
    { part: "4WD Switch" },
    { part: "A/C Accumulator" },
    { part: "A/C Block Off Kit" },
    { part: "A/C Blower Control Unit" },
    { part: "A/C Clutch" },
    { part: "A/C Compressor" },
    { part: "A/C Compressor Clutch Kit" },
    { part: "A/C Compressor Control Valve" },
    { part: "A/C Compressor Kit" },
    { part: "A/C Condenser" },
    { part: "A/C Condenser and Receiver Drier Assembly" },
    { part: "A/C Condenser Fan Assembly" },
    { part: "A/C Condenser Fan Motor" },
    { part: "A/C Condenser Fan Shroud" },
    { part: "A/C Control Panel" },
    { part: "A/C Control Switch" },
    { part: "A/C Evaporator" },
    { part: "A/C Evaporator Core Repair Kit" },
    { part: "A/C Evaporator Temperature Sensor" },
    { part: "A/C Heater Control" },
    { part: "A/C Hose" },
    { part: "A/C Liquid Line Assembly" },
    { part: "A/C Liquid Line with Orifice Tube" },
    { part: "A/C Manifold Hose Assembly" },
    { part: "A/C Pipe" },
    { part: "A/C Pressure Switch" },
    { part: "A/C Receiver Drier" },
    { part: "A/C Receiver Drier with Hose Assembly" },
    { part: "A/C Refrigerant Discharge / Suction Hose Assembly" },
    { part: "A/C Refrigerant Discharge Hose" },
    { part: "A/C Refrigerant Liquid Hose" },
    { part: "A/C Refrigerant Suction Hose" },
    { part: "A/C Refrigerant Temperature Sensor" },
    { part: "A/C Selector Switch" },
    { part: "A/C Servo" },
    { part: "A/C Suction and Liquid Line Hose Assembly" },
    { part: "A/C Suction Line Hose Assembly" },
    { part: "A/C Wiring Harness" },
    { part: "A/T Fluid" },
    { part: "ABS Accumulator" },
    { part: "ABS Control Unit" },
    { part: "ABS Hydraulic Unit" },
    { part: "ABS Modulator Valve" },
    { part: "ABS Pump" },
    { part: "ABS Ring" },
    { part: "ABS Speed Sensor" },
    { part: "ABS Speed Sensor Kit" },
    { part: "ABS Wheel Speed Sensor Set" },
    { part: "ABS Wheel Speed Sensor Wire Harness" },
    { part: "Accelerator Pedal" },
    { part: "Accelerator Pedal Assembly" },
    { part: "Accelerator Pedal Sensor" },
    { part: "Accessory Belt Idler Assembly" },
    { part: "Accessory Belt Idler Pulley" },
    { part: "Accessory Belt Tension Adjuster" },
    { part: "Accessory Belt Tension Pulley" },
    { part: "Accessory Belt Tensioner" },
    { part: "Accessory Belt Tensioner Assembly" },
    { part: "Accessory Drive Belt Kit" },
    { part: "Accessory Shaft Coupling Kit" },
    { part: "Accumulator" },
    { part: "Air Bag Clockspring" },
    { part: "Air Bag Sensor Connector" },
    { part: "Air Compressor" },
    { part: "Air Distribution Duct Clip" },
    { part: "Air Duct Housing" },
    { part: "Air Filter" },
    { part: "Air Filter Housing" },
    { part: "Air Filter Housing Clamp" },
    { part: "Air Filter Set" },
    { part: "Air Flap Actuator" },
    { part: "Air Fuel Ratio Sensor" },
    { part: "Air Inject Check Valve" },
    { part: "Air Intake Heater Relay" },
    { part: "Air Intake Hose" },
    { part: "Air Intake Hose Set" },
    { part: "Air Intake Kit" },
    { part: "Air Intake Resonator" },
    { part: "Air Lift Leveling Kit" },
    { part: "Air Mass Meter" },
    { part: "Air Mass Meter Boot" },
    { part: "Air Mass Meter Hose" },
    { part: "Air Mass Sensor" },
    { part: "Air Mass Sensor Clip" },
    { part: "Air Pump" },
    { part: "Air Pump Check Valve" },
    { part: "Air Pump Control Valve" },
    { part: "Air Pump Hose" },
    { part: "Air Pump Rubber Mount" },
    { part: "Air Spring" },
    { part: "Air Spring Conversion Kit" },
    { part: "Air Spring to Coil Spring Conversion Kit" },
    { part: "Air Strut and Shock Kit" },
    { part: "Air Suspension Compressor and Strut Kit" },
    { part: "Air Suspension Compressor Kit" },
    { part: "Air Suspension Compressor Strut Spring Kit" },
    { part: "Air Suspension Shock" },
    { part: "Air Suspension Solenoid Valve Unit" },
    { part: "Air Suspension Spring Set" },
    { part: "Air Suspension Strut Set" },
    { part: "Air Temperature Sensor" },
    { part: "Alignment Cam Bolt" },
    { part: "Alignment Camber Lateral Link" },
    { part: "Alignment Caster Camber Kit" },
    { part: "Alternator" },
    { part: "Alternator Cable" },
    { part: "Alternator Mount Bracket" },
    { part: "Alternator Pulley" },
    { part: "Altitude Sensor" },
    { part: "Antenna" },
    { part: "Antenna Base" },
    { part: "Antenna Bracket" },
    { part: "Antenna Cover" },
    { part: "Antenna Mast" },
    { part: "Antenna Seal" },
    { part: "Audio Amplifier" },
    { part: "Auto Dual Clutch Actuator" },
    { part: "Auto Trans Filler Tube" },
    { part: "Auto Trans Master Repair Kit" },
    { part: "Auto Trans Oil Cooler Hose Assembly" },
    { part: "Auto Trans Oil Cooler Tube" },
    { part: "Auto Trans Oil Pan and Filter Kit" },
    { part: "Auto Trans Oil Pressure Switch" },
    { part: "Auto Trans Shift Cable Bushing" },
    { part: "Auto Trans Shift Cover Plate" },
    { part: "Auto Trans Shift Lever Assembly" },
    { part: "Auto Trans Shift Lever Button" },
    { part: "Auto Trans Shift Lever Kit" },
    { part: "Auto Trans Shift Lever Knob" },
    { part: "Auto Trans Shift Lever Solenoid" },
    { part: "Auto Trans Shift Tube" },
    { part: "Auto Trans Shifter Cable Kit" },
    { part: "Auto Trans Shifter Repair Kit" },
    { part: "Auto Trans Solenoid Gasket" },
    { part: "Auto Trans Solenoid Kit" },
    { part: "Auto Trans Throttle Valve Cable" },
    { part: "Auto Trans Torque Converter" },
    { part: "Auto Transmission Shift Cable" },
    { part: "Automatic Transmission Cooling Hose" },
    { part: "Automatic Transmission Dipstick" },
    { part: "Automatic Transmission Filter" },
    { part: "Automatic Transmission Filter Kit" },
    { part: "Automatic Transmission Input Shaft Speed Sensor" },
    { part: "Automatic Transmission Oil Cooler" },
    { part: "Automatic Transmission Output Shaft Speed Sensor" },
    { part: "Automatic Transmission Pan" },
    { part: "Automatic Transmission Pan Gasket" },
    { part: "Automatic Transmission Selector Cable" },
    { part: "Automatic Transmission Selector Handle" },
    { part: "Automatic Transmission Shift Linkage Bushing" },
    { part: "Automatic Transmission Solenoid" },
    { part: "Automatic Transmission Speed Sensor" },
    { part: "Automatic Transmission Wire Harness" },
    { part: "Auxiliary Air Valve" },
    { part: "Auxiliary Engine Cooling Fan Assembly" },
    { part: "Auxiliary Fan Assembly" },
    { part: "Auxiliary Fan Control Unit" },
    { part: "Auxiliary Fan Motor" },
    { part: "Auxiliary Fan Resistor" },
    { part: "Auxiliary Fan Switch" },
    { part: "Auxiliary Water Pump" },
    { part: "AWD Coupling Oil Pump" },
    { part: "Axle and Wheel Bearing Kit" },
    { part: "Axle and Wheel Hub Assembly Kit" },
    { part: "Axle Assembly" },
    { part: "Axle Ball Joint Tie Rod End Kit" },
    { part: "Axle Bearing and Hub Assembly Repair Kit" },
    { part: " Axle Bearing Carrier" },
    { part: "Axle Differential Bearing and Seal Kit" },
    { part: "Axle Flip Kit" },
    { part: "Axle Nut" },
    { part: "Axle Seal" },
    { part: "Axle Shaft" },
    { part: "Axle Shaft Bearing" },
    { part: "Axle Shaft Bearing Kit" },
    { part: "Axle Shaft Kit" },
    { part: "Axle Shaft Seal" },
    { part: "Axle Shaft Set" },
    { part: "Axle Shaft Universal Joint" },
    { part: "Axle Spindle" },
    { part: "Axle Wheel Hub Ball Joint Tie Rod Kit" },
    { part: "Axle Wheel Hub Tie Rod End Kit" },
    { part: "Back Glass Lift Support Kit" },
    { part: "Back Up Lamp Assembly" },
    { part: "Back Up Lamp Connector" },
    { part: "Back Up Lamp Socket" },
    { part: "Back Up Light" },
    { part: "Back Up Light Lens" },
    { part: "Back Up Light Switch" },
    { part: "Balance Shaft" },
    { part: "Balance Shaft Kit" },
    { part: "Ball Joint" },
    { part: "Ball Joint and Tie Rod End Kit" },
    { part: "Ball Joint and Tie Rod Kit" },
    { part: "Ball Joint Kit" },
    { part: "Ball Joint Set" },
    { part: "Ball Joint Shim" },
    { part: "Ball Joint Sway Bar Link Tie Rod End Kit" },
    { part: "Ball Joint Tie Rod and Center Link Kit" },
    { part: "Ball Joint Tie Rod End Center Link Kit" },
    { part: "Ball Joint Tie Rod End Drag Link Kit" },
    { part: "Ball Joint Tie Rod End Idler Arm Kit" },
    { part: "Ball Joint Tie Rod Pitman Idler Arm Kit" },
    { part: "Ball Joints Tie Rods Idler and Pitman Arm Kit" },
    { part: "Ball Joints Tie Rods Sway Bar Link Idler and Center Link Kit" },
    { part: "Ball Joints Tie Rods Sway Bar Link Kit" },
    { part: "Ball Joints Tie Rods Sway Bar Links Idler and Pitman Arm Kit" },
    { part: "Ball Joints Tie Rods Sway Bar Links Idler Arm Kit" },
    { part: "Battery" },
    { part: "Battery Cable" },
    { part: "Battery Cable Harness" },
    { part: "Battery Cable Positive" },
    { part: "Battery Cover" },
    { part: "Battery Current Sensor" },
    { part: "Battery Current Sensor Connector" },
    { part: "Battery Power Distribution Box" },
    { part: "Battery Terminal" },
    { part: "Battery Tray" },
    { part: "Bed Mat" },
    { part: "Bed Rail to Rail Tool Box" },
    { part: "Bed Side Rail Protector" },
    { part: "Belt Tensioner Kit" },
    { part: "Blind Spot Detection System Warning Sensor" },
    { part: "Blower Control Switch" },
    { part: "Blower Motor" },
    { part: "Blower Motor Regulator" },
    { part: "Blower Motor Resistor" },
    { part: "Blower Motor Switch" },
    { part: "Blower Motor Wiring Harness" },
    { part: "Body A-Pillar Trim Panel" },
    { part: "Body Harness Connector" },
    { part: "Body Lowering Kit" },
    { part: "Body Mount" },
    { part: "Body Mount Set" },
    { part: "Body Seal Kit" },
    { part: "Boost Pressure Sensor" },
    { part: "Boost Pressure Valve" },
    { part: "Booster Vacuum Hose" },
    { part: "Booster Vacuum Switch" },
    { part: "Brake / Tail / Turn Signal Light Connector" },
    { part: "Brake Adjuster" },
    { part: "Brake and Clutch Pedal Assembly" },
    { part: "Brake Backing Plate" },
    { part: "Brake Booster" },
    { part: "Brake Booster Line" },
    { part: "Brake Booster Vacuum Hose" },
    { part: "Brake Booster Vacuum Pump" },
    { part: "Brake Caliper" },
    { part: "Brake Caliper Bolt" },
    { part: "Brake Caliper Carrier" },
    { part: "Brake Caliper Set" },
    { part: "Brake Drum" },
    { part: "Brake Drum and Brake Shoe Kit" },
    { part: "Brake Drum Set" },
    { part: "Brake Drum Shoe and Wheel Cylinder Kit" },
    { part: "Brake Dust Shield" },
    { part: "Brake Dust Shield Set" },
    { part: "Brake Hose" },
    { part: "Brake Hydraulic Hose Kit" },
    { part: "Brake Hydraulic Hose Set" },
    { part: "Brake Hydraulic Line Kit" },
    { part: "Brake Light" },
    { part: "Brake Line" },
    { part: "Brake Master Cylinder" },
    { part: "Brake Pad and Rotor and Wheel Hub Kit" },
    { part: "Brake Pad and Rotor Kit" },
    { part: "Brake Pad Rotor Shoe Drum Kit" },
    { part: "Brake Pad Sensor" },
    { part: "Brake Pad Sensor Kit" },
    { part: "Brake Pad Set" },
    { part: "Brake Pedal Pad" },
    { part: "Brake Pedal Position Sensor" },
    { part: "Brake Pressure Switch Connector" },
    { part: "Brake Proportioning Valve" },
    { part: "Brake Reservoir" },
    { part: "Brake Rotor" },
    { part: "Brake Rotor and Hub Assembly" },
    { part: "Brake Rotor Set" },
    { part: "Brake Rotor Set Screw" },
    { part: "Brake Shoe Set" },
    { part: "Brake Vacuum Hose" },
    { part: "Breather Hose" },
    { part: "Bug Shield" },
    { part: "Bulb" },
    { part: "Bulb - Headlight" },
    { part: "Bulb Socket" },
    { part: "Bumper" },
    { part: "Bumper Absorber" },
    { part: "Bumper Air Deflector" },
    { part: "Bumper Bracket" },
    { part: "Bumper Cover" },
    { part: "Bumper Cover Bracket" },
    { part: "Bumper Cover Grille" },
    { part: "Bumper Cover Grille Molding" },
    { part: "Bumper Cover Molding" },
    { part: "Bumper Cover Reflector" },
    { part: "Bumper Cover Reinforcement" },
    { part: "Bumper Cover Retainer" },
    { part: "Bumper Cover Shield" },
    { part: "Bumper Cover Stiffener" },
    { part: "Bumper Cover Support" },
    { part: "Bumper Deflector" },
    { part: "Bumper End" },
    { part: "Bumper End Cap" },
    { part: "Bumper Face Bar" },
    { part: "Bumper Filler" },
    { part: "Bumper Grille" },
    { part: "Bumper Grille Insert" },
    { part: "Bumper Grille Molding" },
    { part: "Bumper Guard" },
    { part: "Bumper Impact Bar Brace" },
    { part: "Bumper Impact Strip" },
    { part: "Bumper Insert" },
    { part: "Bumper Molding" },
    { part: "Bumper Moulding" },
    { part: "Bumper Moulding Insert" },
    { part: "Bumper Mounting Kit" },
    { part: "Bumper Protection Pad" },
    { part: "Bumper Reflector" },
    { part: "Bumper Reinforcement" },
    { part: "Bumper Splash Shield" },
    { part: "Bumper Spoiler" },
    { part: "Bumper Trim" },
    { part: "Bumper Valance" },
    { part: "Bypass Hose" },
    { part: "Cab Corner" },
    { part: "Cab Corner and Rocker Panel Kit" },
    { part: "Cab Corner Set" },
    { part: "Cab Protector and Headache Rack" },
    { part: "Cabin Air Filter" },
    { part: "Cabin Air Filter Cover" },
    { part: "Cabin Air Filter Retrofit Kit" },
    { part: "Cabin Air Filter Set" },
    { part: "Caliper Piston" },
    { part: "Cam Follower" },
    { part: "Cam Plug" },
    { part: "Camshaft" },
    { part: "Camshaft Adjuster Magnet" },
    { part: "Camshaft and Crankshaft Position Sensor Kit" },
    { part: "Camshaft Gear" },
    { part: "Camshaft Kit" },
    { part: "Camshaft Position Sensor" },
    { part: "Camshaft Seal" },
    { part: "Camshaft Solenoid Adjuster" },
    { part: "Camshaft Synchronizer" },
    { part: "Cap Emblem" },
    { part: "Car Cover" },
    { part: "Carbon Canister" },
    { part: "Carburetor" },
    { part: "Carburetor Kit" },
    { part: "Carburetor Repair Kit" },
    { part: "Cargo Liner" },
    { part: "Catalytic Converter" },
    { part: "CD ROM Repair Manual" },
    { part: "Center Cap" },
    { part: "Center Console" },
    { part: "Center Console Base" },
    { part: "Center Console Latch" },
    { part: "Central Lock Switch" },
    { part: "Circuit Opening Relay" },
    { part: "Climate Control Module" },
    { part: "Climate Control Push Button Set" },
    { part: "Clutch Cable" },
    { part: "Clutch Flywheel Conversion Kit" },
    { part: "Clutch Hose" },
    { part: "Clutch Hydraulic Line" },
    { part: "Clutch Kit" },
    { part: "Clutch Lever" },
    { part: "Clutch Master Cylinder" },
    { part: "Clutch Master Cylinder and Line Assembly" },
    { part: "Clutch Master/Slave Assembly" },
    { part: "Clutch Pedal" },
    { part: "Clutch Pedal Pad" },
    { part: "Clutch Pedal Stop Pad" },
    { part: "Clutch Release Arm" },
    { part: "Clutch Slave Cylinder" },
    { part: "Clutch Starter Safety Switch" },
    { part: "Clutch Switch" },
    { part: "Coil Spring" },
    { part: "Coil Spring Bracket" },
    { part: "Coil Spring Insulator" },
    { part: "Coil Spring Lowering Kit / Shock Absorber Kit" },
    { part: "Coil Spring Seat Repair Kit" },
    { part: "Coil Spring Set" },
    { part: "Cold Air Intake" },
    { part: "Cold Air Intake Tube" },
    { part: "Cold Start Valve" },
    { part: "Combination Switch" },
    { part: "Combination Valve" },
    { part: "Combustion Detection Module" },
    { part: "Computer Chip Programmer" },
    { part: "Computer Control Relay" },
    { part: "Console Lid" },
    { part: "Control Arm" },
    { part: "Control Arm and Ball Joint Assembly" },
  ];
  return (
    <>
      <div className="showparts">
        <div className="container">
          <div className="d-flex align-items-center mb-3">
            <i className="fa-solid fa-gear fs-2 me-2 main"></i>
            <h3 className="fs-3 fw-bold">Shop More Parts :</h3>
          </div>
          <div className="row">
            {data.map((item, index) => {
              return (
                <div className="col-lg-3 mb-4" key={index}>
                  <div className="card shop-card">
                    <h6 className="pt-1 parts-text text-center">
                      <Link to="">{item.part}</Link>
                    </h6>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}
