import React from 'react'
import { Link } from 'react-scroll'

export default function ShowParts() {
    const data = [
        { part: "ABS Speed Sensor" },
        { part: "AC Compressor" },
        { part: "AC Condenser" },
        { part: "AC Evaporator" },
        { part: "AC Expansion Valve" },
        { part: "AC Heater Control" },
        { part: "AC Hose" },
        { part: "AC Receiver Drier" },
        { part: "Accelerator Pedal Sensor" },
        { part: "Accessory Belt Idler Pulley" },
        { part: "Air Bag Clockspring" },
        { part: "Air Compressor" },
        { part: "Air Fuel Ratio Sensor" },
        { part: "Air Intake Hose" },
        { part: "Air Mass Meter" },
        { part: "Air Mass Meter Boot" },
        { part: "Air Mass Sensor" },
        { part: "Air Pump" },
        { part: "Air Spring" },
        { part: "Antenna" },
        { part: "Antenna Mast" },
        { part: "Automatic Trans Solenoid" },
        { part: "Auto Trans Speed Sensor" },
        { part: "Back Up Light" },
        { part: "Battery Cable" },
        { part: "Belts" },
        { part: "Blower Motor" },
        { part: "Blower Motor Resistor" },
        { part: "Body Lowering Kit" },
        { part: "Brake Booster" },
        { part: "Brake Caliper" },
        { part: "Brake Drum" },
        { part: "Brake Hose" },
        { part: "Brake Hydraulic Line Kit" },
        { part: "Brake Pad Sensor" },
        { part: "Brake Shoes" },
        { part: "Brakes" },
        { part: "Breather Hose" },
        { part: "Bug Shield" },
        { part: "Bumper Absorber" },
        { part: "Bumper Bracket" },
        { part: "Bumper Cover" },
        { part: "Bumper End" },
        { part: "Bumper Face Bar" },
        { part: "Bumper Grille" },
        { part: "Bumper Impact Strip" },
        { part: "Bumper Reinforcement" },
        { part: "Camshaft" },
        { part: "Camshaft Position Sensor" },
        { part: "Car Bra" },
        { part: "Car Cover" },
        { part: "Carbon Canister" },
        { part: "Carburetor" },
        { part: "Clutch Cable" },
        { part: "Clutch Disc" },
        { part: "Clutch Master Cylinder" },
        { part: "Coil Spring" },
        { part: "Coil Spring Conversion Kit" },
        { part: "Cold Start Valve" },
        { part: "Performance Programmer" },
        { part: "Console Lid" },
        { part: "Control Arm Bushing" },
        { part: "Cornering Light" },
        { part: "Crank Position Sensor" },
        { part: "Crankcase Vent Valve" },
        { part: "Crankshaft Pulley" },
        { part: "Cruise Control Module" },
        { part: "Crusive Control Switch" },
        { part: "CV Boot" },
        { part: "CV Joint" },
        { part: "Distributor" },
        { part: "Distributor Cap" },
        { part: "Distributor Rotor" },
        { part: "Door Latch Assembly" },
        { part: "Door Lock Actuator" },
        { part: "Door Mirror Glass" },
        { part: "Driveshaft" },
        { part: "Driveshaft Bearing" },
        { part: "Driveshaft Support" },
        { part: "EGR VAlve" },
        { part: "Electronic Control Unit" },
        { part: "Emblem" },
        { part: "Engine Vibration Damper" },
        { part: "Engine Wiring Harness" },
        { part: "Exhaust Headers" },
        { part: "Exhaust Manifold Gasket" },
        { part: "Exhaust Pipe" },
        { part: "Fan Blade" },
        { part: "Fan Clutch" },
        { part: "Fan Shroud" },
        { part: "Fender" },
        { part: "Flex Joint" },
        { part: "Flex Plate" },
        { part: "Flywheel" },
        { part: "Fog Light Bezel" },
        { part: "Fuel Distributor" },
        { part: "Fuel Filler Neck" },
        { part: "Fuel Filter" },
        { part: "Fuel Injectors" },
        { part: "Fuel Level Sending Unit" },
        { part: "Fuel Pressure Regulator" },
        { part: "Fuel Pump Relay" },
        { part: "Fuel Tank" },
        { part: "Fuel Tank Cap" },
        { part: "Glow Plugs" },
        { part: "Grille Moulding" },
        { part: "Harmonic Balancer" },
        { part: "Hatch Strut" },
        { part: "Hazard Flasher Switch" },
        { part: "Head Bolt" },
        { part: "Header Pipe" },
        { part: "Headlight Bulb" },
        { part: "Headlight Covers" },
        { part: "Headlight Dimmer Switch" },
        { part: "Headlight Mounting Panel" },
        { part: "Headlight Switch" },
        { part: "Heater Core" },
        { part: "Heater Hose" },
        { part: "Heater Valve" },
        { part: "Hood" },
        { part: "Hood Hinge" },
        { part: "Hood Pad" },
        { part: "Hood Release Cable" },
        { part: "Hood Release Handle" },
        { part: "Hood Strut" },
        { part: "Hub Cap" },
        { part: "HVAC Control Module" },
        { part: "Idle Control Valve" },
        { part: "Idler Arm" },
        { part: "Igniter" },
        { part: "Ignition Cassette" },
        { part: "Ignition Control Unit" },
        { part: "Ignition Lock Assembly" },
        { part: "Ignition Lock Cylinder" },
        { part: "Ignition Lock Housing" },
        { part: "Ignition Module" },
        { part: "Ignition Switch" },
        { part: "Impluse Sender" },
        { part: "Inner Fender Well" },
        { part: "Intake Manifold" },
        { part: "Intake Manifold Gasket" },
        { part: "Intake Manifold Runner Valve" },
        { part: "Intercooler" },
        { part: "Intermediate Pipe" },
        { part: "Knock Sensor" },
        { part: "Leaf Spring" },
        { part: "License Plate Bracket" },
        { part: "Locking Hub" },
        { part: "MAP Sensor" },
        { part: "Master Cylinder" },
        { part: "Mud Flaps" },
        { part: "Neutral Safety Switch" },
        { part: "Oil Cooler" },
        { part: "Oil Pump" },
        { part: "Overdrive Relay" },
        { part: "Overdrive Switch" },
        { part: "Park Assist Camera" },
        { part: "Parking Brake Cable" },
        { part: "Parking Light" },
        { part: "Piston Ring Set" },
        { part: "Pitman Arm" },
        { part: "Power Steering Hose" },
        { part: "Preglow Time Relay" },
        { part: "Pressure Plate" },
        { part: "Purge Valve" },
        { part: "Radiator Hose" },
        { part: "Radiator Shutter Assembly" },
        { part: "Radiator Support" },
        { part: "Reference Sensor" },
        { part: "Release Bearing" },
        { part: "Reset Tool" },
        { part: "Rocker Arm" },
        { part: "Seat Cover" },
        { part: "Shifter Bushing" },
        { part: "Shock Absorber" },
        { part: "Shock Mount" },
        { part: "Side Marker" },
        { part: "Skid Plate" },
        { part: "Slave Cylinder" },
        { part: "Soft Top" },
        { part: "Spare Tire Hoist" },
        { part: "Steering Damper" },
        { part: "Steering Gearbox" },
        { part: "Steering Knuckle" },
        { part: "Steering Linkage Assembly" },
        { part: "Steering Rack" },
        { part: "Step Bumper" },
        { part: "Strut Bellows" },
        { part: "Strut Mount" },
        { part: "Struts" },
        { part: "Sunroof Handle" },
        { part: "Sunroof Motor" },
        { part: "Sunroof Seal" },
        { part: "Suspension Kit" },
        { part: "Sway Bar Bushing" },
        { part: "Sway Bar Link" },
        { part: "Tail Light Covers" },
        { part: "Tail Lights Guards" },
        { part: "Tailgate" },
        { part: "Tailgate Handle" },
        { part: "Tailgate Net" },
        { part: "Tailgate Strut" },
        { part: "Thermostat" },
        { part: "Thermostat Housing" },
        { part: "Third Brake Light" },
        { part: "Throttle Body" },
        { part: "Throttle Body Spacer" },
        { part: "Throttle Position Sensor" },
        { part: "Timing Belt Tensioner" },
        { part: "Timing Chain" },
        { part: "Timing Chain Tensioner" },
        { part: "Timing Cover" },
        { part: "TPMS Sensor" },
        { part: "Trailer Hitch" },
        { part: "Trailing Arm" },
        { part: "Transfer Case Motor" },
        { part: "Transmission Filter" },
        { part: "Transmission Mount" },
        { part: "Trunk Seal" },
        { part: "Trunk Strut" },
        { part: "Turbocharger" },
        { part: "Turn Signal Switch" },
        { part: "Vacuum Pump" },
        { part: "Valance Panel" },
        { part: "Valve Cover" },
        { part: "VAlve Cover Gasket" },
        { part: "Vapor Canister Vent Solenoid" },
        { part: "Variable Timing Solenoid" },
        { part: "Washer Pump" },
        { part: "Washer Reservior" },
        { part: "Wheel Bearing" },
        { part: "Wheel Cover" },
        { part: "Wheel Cylinder" },
        { part: "Wheelhouse Molding" },
        { part: "Window Vent Visors" },
        { part: "Windshield Wiper Arm" },
        { part: "Windshield Wiper Switch" },
    ]
    return (
        <>
            <div className="showparts">
                <div className="container">
                    <div className="d-flex align-items-center mb-3">
                        <i className="fa-solid fa-gear fs-2 me-2 main"></i>
                        <h3 className="fs-3 fw-bold">Shop More Parts :</h3>
                    </div>
                    <div className="row">
                        {data.map((item, index) => {
                            return (
                                <div className="col-lg-3 mb-4" key={index}>
                                    <div className="card shop-card" >
                                        <h6 className='pt-1 parts-text text-center'><Link to="">{item.part}</Link></h6>
                                    </div>

                                </div>
                            )
                        })}

                    </div>

                </div>
            </div>
        </>
    )
}
